### ISSUE TITLE
Naming Conventions

### ISSUE THREAD

**Issue by helgestein** [helgestein/helao-pub#47]
Some naming conventions are confusing to me i.e. force and forcesdc. To me it is right now clear that one refers to the GSV2USB and the other to the GSV3USB but who knows what will be in a few years time. Considering that we're not using the minipump or the forcesensor by sensolytics anymore we could also delete the file. However the confusion becomes even worse in the launch GUI. I would opt for either adding some kind of bar seperating actions and drivers OR namin them less confusin the user script.

**Comment by darthlegit** [comment]
The drivers should be named in a way that it is obvious what is what, which is why I have leaned more towards naming the driver/action after the device manufacturer when I get to decide. I am for renaming both the pump drivers/actions and force drivers/actions accordingly.

**Comment by fuzhanrahmanian** [comment]
yeah, it was confusing to put company name on the drivers and I don't think it is a good idea to remove the code completely. Minipump is still in use, so maybe in the documentation, we can explain the difference between different pumps and so on. This repo eventually should not be just for the sake of our use but also other laboratories so if we not maybe they have those force and pump system. This is why i am more on just renaming and explaining in doc rather than deleting it completely.
